AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: 'vpc'

Outputs:
  VPNEIP:
    Description: EIP for VPN instance
    Value: !GetAtt EIP.AllocationId
    Export:
      Name: !Sub "${AWS::StackName}-EIPAllocationId"